server:
  port: 8080

springdoc:
  show-login-endpoint: true
# DB configurations
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    database: POSTGRESQL
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/hcl-db-local
    initialization-mode: always
    username: postgres
    password: postgres
    # DB Connection pooling
    hikari:
      schema: public
      #maximum pool size
      maximum-pool-size: 25
      #maximum number of milliseconds that a client will wait for a connection
      connection-timeout: 40000
      #minimum number of idle connections maintained by HikariCP in a connection pool
      minimum-idle: 2
      #maximum idle time for connection
      idle-timeout: 10000
      # maximum lifetime in milliseconds of a connection in the pool after it is closed.
      max-lifetime: 30000



